### ISSUE TITLE
Sponsor Agile DevOps East - Orlando

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#11]
# Sponsor Agile DevOps East - Orlando

## User Story

As a co-organizer of Orlando DevOps group, I would like to start by investigating sponsoring the [Agile DevOps East conference (Expo)](https://agiledevopseast.techwell.com/expo/about-expo) in Orlando so that we can spread the word more about Orlando DevOps and anything we do in the future.

## Tasks

- [x] Contact TechWell the Organizers
- [ ] Determine if there is a cost
- [ ] Will we be able to staff a booth
- [ ] Can we get some stickers or other give away things?

## Extra Notes

> NOTE: None right now, but I am sure I will think of something.

**Comment by snohio** [comment]
I completed the form for inquiry about sponsoring. Will check back in a few days.
