### ISSUE TITLE
October, 2023 - Monthly Meeting Agenda

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#16]
# October 2nd, 2023 - Monthly Meeting Agenda

Time: 8:00 PM - 9:00 PM

## Meeting Place / Zoom Link

Join on [Zooooom](https://progress.zoom.us/my/chef.mike)

### Done / Review

- [x] DevOpsDays Tampa Review. There wasn't a card for this, but curious of thoughts.
- [x] #2 - Discuss the results thus far. We need to keep pushing this survey. 21 was good, but let's keep it going!
- [x] #13
- [x] #4 Review and Close

### Doing / Blocked:

- [x] #6 - Let's get these files in an /assets folder in this repo and close!
- [x] #11 - Still not getting an answer back. I've emailed and LinkedIn Message the person.
- [x] #7 - Brian announced us right? I think a LinkedIn Post / other socials? and we are done.
- [x] #9 - Using the results from the Survey, let's circle back to this at the end.
- [x] #8 - Working with Lauren to get access to Google Workspace and GitHub. Those are my two big ones.
- [x] #14 - This seems in Active Process. Let's take notes on that card.

### Ready Tasks:

- [x] None right now

### Backlog:

- [x] #3 - I moved to Backlog because I'd rather just become an admin of O-Devs GitHub Org.

## Things needing a card

- [x] Follow up to #11 - do we want an attending card? See Lean Beer, do we want to host one in that area or even do an Open Spaces that evening (the 8th) That is actually our "monthly" meetup date.
- [x] Upcoming Meetups (Let's get cards for October, November, December Lean events. Let's brainstorm on those events.)
- [x] Orlando DevFest - GDG 
- [x] DevOpsDays Site Discovery (I'm kinda high on this one right now)

## Review the MILESTONES 

- [x] [Q3-23 Milestones](https://github.com/snohio/devopsorlando/milestone/1)
Let's close this milestone and start working on Q4-23 Milestone.
- [x] [Q4-23 Milestones](https://github.com/snohio/devopsorlando/milestone/2)
Review the goals that I've laid forth for October - December of 2023. 

## Wrap Up

So long and thanks for all the fish!

**Comment by snohio** [comment]
Meeting Over. Sorry for taking 2 hours. ❤️
