### ISSUE TITLE
Find a Social Media Manager

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#17]
# Find a Social Media Manager

## User Story

As a co-organizer of Orlando DevOps group, I would like to find a Social Media Manager so that Orlando DevOps can exist across multiple social networks.

## Tasks

- [x] Go through [survey](https://github.com/snohio/devopsorlando/issues/2) and find candidates

| Contact info | Current socials | Survey response
| -------------- | ---------------- | ----------------- |
Hiers.jacob@gmail.com | LinkedIn<br>Slack | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNhZkkxdR9tL9ciJQYNj5ItHIlFxNqRfi2ht3w1vvSqIi5R9cAKkYWumFGz2PimtxT8)
Duncansabatino@protonmail.com <br> 928-399-8771 | none | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNgSOprervATc9cP7F8LJP84eMu9cR_AcLgfdYnKdIdL5U2CimCan6w91fl8kA1rCPc)
reneyka14@gmail.com <br> 352-608-9851 | Instagram<br>LinkedIn | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNj-SGmZutrs32s1vnJ_jtprF-5urbYnjGBJ673vBIbwV4OLul4yz4ciRFPg-Qsfl1w)
mhniceguy@gmail.com | FaceBook<br>LinkedIn<br>Mastodon | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNh1eD2eXZjL-2OEWrqXSazYt1anMB1zKGwOVF1QWnCBS7jI1bCfAktj_AayWRwAM00)
javi@devfestflorida.org | FaceBook<br>Instagram<br>LinkedIn<br>Mastodon<br>Threads<br>X (FKA Twitter) | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNiCuzwTBQnGzYbL4wsAa1_zYui1hAmm4DOcSVFNEszTmCfQdpVCs7jfYS6AvVFmt-U)
mr.denver.martin@gmail.com | Facebook<br>Instagram<br>LinkedIn<br>X (FKA Twitter) | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNg2GcycefVAACjcc-VfDqfNOJ5YYsAH-BWliAEOI2PyV7TrDLYnKeIHwJkccDOTQk0)
bclincy@gmail.com | Facebook<br>Instagram<br>LinkedIn<br>Threads<br>X (FKA Twitter) | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNghtEnauYTLNkS6yrzVqo2Di5djJPMzAXuIjBWptFAjmKbUIS34-wDI6eZZ4y7p9S0)
deb.splunk@gmail.com | FaceBook<br>LinkedIn | [link](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNj5I4Lxx1w1xeUk5RnZ4bEHwuU-v-ZXMerENZ9nANZyuyqIlln15QGCNbc15iQUU70)
- [ ] Send them a message
  - We want to crosspost events across various socials: LinkedIn, Meetup, O'Devs (to get on their slides), email, maybe Slack
  - We want to crosspost reminders across the same socials, maybe a few days or a week out
- [ ] Get responses
- [ ] Find the person for the job

**Comment by mbuchoff** [comment]
The following people said they would be interested in assisting (besides the current organizers):
Hiers.jacob@gmail.com - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNhZkkxdR9tL9ciJQYNj5ItHIlFxNqRfi2ht3w1vvSqIi5R9cAKkYWumFGz2PimtxT8)
Duncansabatino@protonmail.com, 928-399-8771 - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNgSOprervATc9cP7F8LJP84eMu9cR_AcLgfdYnKdIdL5U2CimCan6w91fl8kA1rCPc)
reneyka14@gmail.com, 352-608-9851 - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNj-SGmZutrs32s1vnJ_jtprF-5urbYnjGBJ673vBIbwV4OLul4yz4ciRFPg-Qsfl1w)
mhniceguy@gmail.com - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNh1eD2eXZjL-2OEWrqXSazYt1anMB1zKGwOVF1QWnCBS7jI1bCfAktj_AayWRwAM00)
javi@devfestflorida.org - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNiCuzwTBQnGzYbL4wsAa1_zYui1hAmm4DOcSVFNEszTmCfQdpVCs7jfYS6AvVFmt-U)
mr.denver.martin@gmail.com - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNg2GcycefVAACjcc-VfDqfNOJ5YYsAH-BWliAEOI2PyV7TrDLYnKeIHwJkccDOTQk0)
bclincy@gmail.com - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNghtEnauYTLNkS6yrzVqo2Di5djJPMzAXuIjBWptFAjmKbUIS34-wDI6eZZ4y7p9S0)
deb.splunk@gmail.com - [survey response](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit#response=ACYDBNj5I4Lxx1w1xeUk5RnZ4bEHwuU-v-ZXMerENZ9nANZyuyqIlln15QGCNbc15iQUU70)

**Comment by snohio** [comment]
Do you want me to send out the email? We should document some expectations / desires / roles that we want that person to do.

**Comment by mbuchoff** [comment]
@snohio, sure. Thanks! I was wondering if we should start with Jacob, since we all know and like him and he's helped a bit already.

Also, not sure if GitHub sends updates when the description is updated, but the table at the top is easier to read.

**Comment by snohio** [comment]
We can start with Jacob. Do you want to reach out to him or I can!

**Comment by mbuchoff** [comment]
Either works for me. I'll start putting together a list of things to mention/questions to ask tomorrow.

**Comment by mbuchoff** [comment]
@snohio, I'm realizing I don't have a clear idea of what this should be, besides crossposting events and reminders, so I think it's better if you reach out.

**Comment by mbuchoff** [comment]
@snohio, can you add Jacob as a contributor to our GitHub repo?

**Comment by snohio** [comment]
@jehiers has graciously accepted the role.
