### ISSUE TITLE
Investigate locations for DevOps Days

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#19]
# Investigate locations for DevOps Days

## User Story

As a co-organizer of Orlando DevOps group, I would like to find a location for hosting a DevOps Days convention so that we are able to host a DevOps Days convention.

## Tasks

- [ ] Determine criteria (expected amount of people, budget, etc)
- [ ] Come up with a list of candidates
- [ ] Investigate each candidate
- [ ] Pull the trigger

## Extra Notes

@snohio has many ideas on this
