### ISSUE TITLE
Check on Sponsorship for Orlando Code Camp

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#25]
# Check on Sponsorship for Orlando Code Camp

## User Story

As a co-organizer of the Orlando DevOps group, I would like to Follow up with Orlando Code Camp about a small table so that can give out stickers and information 

## Tasks

- [x] Email the organizers - see if they will offer us a free Community table
- [x] Reach out to ODevs and other community groups if they would be interested in joining (Board Meeting Friday 2/16)
- [x] Promote the heck out of Orlando Code Camp between now and Feb 23rd
- [ ] If invited, prepare the media and stickers to hand out and post

**Comment by snohio** [comment]
Email sent::

>Hello Orlando Code Camp Team!

>
>  I am excited to be presenting this year at Orlando Code Camp! I'm not sure if you knew this, but I am one of the leadership members of the Orlando DevOps Community Group (meetups.) We are rapidly (re)growing our community and hosting two events a month in the domain of DevSecOps in the Orlando area. We are a member of the Orlando Devs organization and fall under their non-profit status.

>
>  I am reaching out to inquire about the availability of a small table in the sponsor area at the Orlando Code Camp this year to mainly hand out some stickers, have some QR codes for our group, and have conversations about participating in our meetings. I have participated in several DevOpsDays events across the US and they offer community tables to folks not selling anything for free. I am curious if it would be possible setup a small table on the 24th.

>
> Please let me know so that we can plan accordingly!

>
> Thank you,
> Mike Butler
> Co-organizer Orlando DevOps Community Group
> LinkedIn [(7) Orlando DevOps Community Group | Groups | LinkedIn](https://www.linkedin.com/groups/12876376/)
> MeetUp [Orlando DevOps | Meetup](https://www.meetup.com/orlando-devops/)

**Comment by snohio** [comment]
Response back from Andy: TL;DR is - we might be able to, but a decision will be made closer to the event and based on if and how well we promote Code Camp. So let's promote code camp everywhere!

> Hi, Mike.

>
> It is part of the plan to have some space for a few community groups, but I can't say yet whether it will be one shared table or more.  We are still figuring out how many tables we will be able to have with first priority to our paying sponsors, of course.

>
> We have existing relationships with GDG Central Florida and SQLOrlando who also run events at Seminole State and have cross-promoted our events and us theirs.  If your group could also promote Orlando Code Camp through the site and the Eventbrite link, that would help us get the message out.  If the larger Orlando Devs organization could do that as well, even better.

>
> [Orlando Code Camp](https://orlandocodecamp.com/)
> [Get Your Ticket Here For Free](https://www.eventbrite.com/e/800584980227/?aff=oddtdtcreator)

> 
> Thanks,
> Andy Lech

**Comment by snohio** [comment]
I missed Friday's call due to it being a family day and PTO. I was out and about since the boys were off school. Due to the close nature, I don't think anyone is going to get organized for it. I have posted in a few places. Let me know if anyone else posted on their LinkedIn or elsewhere. I'll follow up with them on Monday the 19th.
