### ISSUE TITLE
Reach out to StarEast for Community Table

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#26]
# Reach out to StarEast for Community Table

## User Story

As a co-organizer of the Orlando DevOps group, I would like to investigate the ability to get a free Community Table at the StarEast conference so that spread the word about Orlando DevOps

## Tasks

- [ ] Reach out to Kim Trott (See email in Notes
- [ ] Determine if we can set up a free small table (with our 501c3 status)
- [ ] If there is a cost, reach out to the ODevs to see if there would be interest in a full group table.

## Extra Notes

> APRIL 28 – MAY 3, 2024 
>
> [Website](https://stareast.techwell.com/)

NOTE: Here is the email I have from them:
> Hi Michael,
>
>This year STAREAST is already looking to be an even bigger blowout, with no shortage of opportunities for sponsors like you to get meaningful exposure. In case you missed it, here is a [highlight reel](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bA9BmDoXZW7GEQZ6R0UlghUWnV0rFBZFxTmdkCkYMr0EEZtkbeQzxAjcTpt7bxTUsRs=) from the previous year. Don't miss out on the opportunity of getting in front of a captive audience where you can showcase your products in-person to delegates willing to make the investment in your solution.
>
> Below are only a few of the stellar reviews we received from fellow attendees about their [STAREAST conference](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bANz93wUeXG3CjYXWL0NJGOQZKv1mfO1CAau0WzqU2fgxi41cUafJ-R5qM56s6b70Mk=) experience:
>
> "There’s so many amazing talks and keynotes and workshops. It’s definitely an event you don’t want to miss. If there’s any testing conference in North America to hit up, it’s the STAR conferences.”
>
> “My favorite part is the awesome networking experience. I’ve gotten to meet so many people that have blown my mind and taught me awesome things..."
>
> “It was a huge pleasure to be [at STAREAST]. The experience, the vibe here is so high, people are friendly and I had the opportunity to meet a lot of people..."
>
> “…We’ve been a sponsor at many TechWell events, STARWEST, STAREAST, and the Agile + DevOps conferences. We love coming to these events every year because we get to meet interesting people in the testing community, people that are worried about test automation, artificial intelligence, and all the latest trends."
>
> Sponsors tell me all the time how TechWell conferences generate great leads for them. See for yourself—I'd love to have you join us for the biggest and best Test / QA conference in the WORLD! As always, drinks on me :)
>
> For additional info, look through our brand new [2024 Media Kit](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bBUdTzci2n6cBRkyTcRTpZ09lClEposPhCvxydhPML6oJHbrqMnyQHEpz-d9SzJg8eU=) . There's a demographic breakdown of the TechWell audience on pages 3-4, as well as a full list of sponsor and exhibitor benefits on pages 7-8.
>
> Please [find a time on my calendar](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bE1vjZTluSpjxZ_atIKm45FtlhVyGMENgqwl4pizJD0jMA0_N-Ig9he899gdiBw6fp0=)to meet or give me a call to discuss your strategy for the upcoming year. I'd be happy to offer recommendations and help you optimize your budget for 2024.
> 
> Here to help,
>
> Kim Trott, TechWell
> Director, Business Development and Partnerships
> Cell: 410.340.4488
> [ktrott@techwell.com](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bA3j5NMFN6T0gj9dxdXIQSQjQAYbhCQLY2dbCA7HYouGy8Fe-pFzi1FBllw1WvGpZoM=)
> Connect with me on [LinkedIn](https://email.techwell.com/MzM1LUZFTC0yMTUAAAGQ_wH4bKyb9YaRHe2LeqKgx01WopPLFfz8Zk634tJxBLJu67pnMOuPjyBSqDPmXhlcSwFG0Xg=)

**Comment by snohio** [comment]
I'm going to close this. I don't think they are going to let us come for free. We can work on them for the Agile DevOps US conference in October.
