### ISSUE TITLE
Create a new Survey - call it the Semi-annual survey

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#27]
# Create a new Survey - call it the Semi-annual survey

## User Story

As a co-organizer of the Orlando DevOps community group, I would like to have a new survey created and promoted so that we can gauge interest in topics, events and other things

## Tasks

- [x] Update these TASKS with all that is needed. Reference #2 
- [x] Create a Survey in the snohio@google.com /devops/ Drive folder. You can duplicate the old one.
  - [link to new survey](https://docs.google.com/forms/d/1Wun1EAB1fQPaOsXX8NDetXSDViJRMkPJpL7haAhcPHk)
- [x] Update it and add the questions below

### Some new things we are interested in.

- [x] Would you pay $50 for a one-day [Unconference](https://en.wikipedia.org/wiki/Unconference) in Orlando this summer?
- [x] Would you be interested in purchasing an Orlando DevOps T-shirt for $25 (publish [image](https://orlandodevs.slack.com/files/US60GSMEF/F06KST9F0AF/image.png))
- [x] Would you participate in a Patreon donation fund for our Community Group (1/5/10 per month)

## Extra Notes

> Let @snohio know if you need help.

**Comment by mbuchoff** [comment]
@snohio,
> Would you pay $50 for a one-day [Unconference](https://en.wikipedia.org/wiki/Unconference) in Orlando this summer?

Is this question referring to an Unconference with the Orlando DevOps group or just in general?

**Comment by mbuchoff** [comment]
Just started working on it.

[link](https://docs.google.com/forms/d/1Wun1EAB1fQPaOsXX8NDetXSDViJRMkPJpL7haAhcPHk/edit)

**Comment by snohio** [comment]
> Is this question referring to an Unconference with the Orlando DevOps group or just in general?

I am thinking of seeing if there is interest for all ODevs Community Groups to do an All ODEVS one. So in that regard - in general. I'd like to gather interested in a paid unconference. We just don't have the sponsorship like Code Camp has to do something free. Given the time, we'd likely not get many sponsors to do it. Unconferences are supposed to be pretty open. The $50 is for space and food, basically.

**Comment by mbuchoff** [comment]
@RecoveringChef, do you have an image of a Orlando DevOps t-shirt that I can use?

**Comment by mbuchoff** [comment]
Note for the next semiannual survey:
- How many events have you been to?
- Add the day of week question back in.

**Comment by snohio** [comment]
I made a few minor changes. I'm not sure if I really care to ask the social media questions again, although a "Do you prefer to sign up on Meetup or eventbrite?" would be good to know.

**Comment by snohio** [comment]
I'd like to have this done by 2/23 so I can print a QR code and put it in my slide deck as well.

**Comment by mbuchoff** [comment]
@snohio, I just re-read through the survey and I think it's complete.

**Comment by mbuchoff** [comment]
@snohio, I'm going to advance the status of this issue, but if you disagree, feel free to kick it back.
