### ISSUE TITLE
Reorder 300 Orlando DevOps Stickers

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#28]
# Reorder 300 Orlando DevOps Stickers

## User Story

As a co-organizer of the Orlando DevOps Community group, I would like to have another set of stickers ordered so that have them available for Orlando Code Camp #25 

## Tasks

- [x] Reference #13 for the sticker information for reorder
- [ ] Track the purchase on [Expenses](https://github.com/snohio/devopsorlando/blob/main/expenses.md)
- [ ] Distribute to the ODO Organizer members

**Comment by snohio** [comment]
@mdaverde BE sure to track. 
It also looks like they are expected to be at my house on Tuesday. I'll confirm when I received them. Thanks for the Mule Sauce.

**Comment by snohio** [comment]
I received the stickers. I'll get them distributed the next time I see you all.

**Comment by mbuchoff** [comment]
Can we close this issue?

**Comment by snohio** [comment]
Yeah, I moved it to Done but didn't close.
