### ISSUE TITLE
Get a few shirts for Orlando Code Camp and for the Organizers

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#29]
# Order Orlando DevOps T-shirts

## User Story

As a co-organizer of the Orlando DevOps Community group, I would like to have t-shirts available for staff so that wear them at the Orlando Code Camp event and help promote our group.

## Tasks

- [x] Determine sizes needed
- [x] Place the order
- [ ] Put the order on [Expense](https://github.com/snohio/devopsorlando/blob/main/expenses.md)
- [x] Deliver to the staff

## Extra Notes

> THIS NEEDS TO BE COMPLETED AND SHIPPED BY FEB 16th.
> 
> Reach out to @RecoveringChef for information on where he bought them if he is not going to order them.

## Sizes Needed

- [x] Mike Butler - Large
- [x] Mike Buchoff - Large

**Comment by RecoveringChef** [comment]
DARK shirts
https://www.printful.com/product-template/57412421/52d2a145108a82ce89938575eeb1860d

LIGHT shirts
https://www.printful.com/product-template/65691517/513c671a894c5c438a88b60e17dd45b0

**Comment by mbuchoff** [comment]
I think we can move this to _Done_, given that Code Camp has passed and many of us already have shirts. Everyone agree?

**Comment by snohio** [comment]
Should we promote this anywhere for folks to order their own?

**Comment by mdaverde** [comment]
We can add a slide to the deck we're meant to show at each event with a QR code to the order page?

**Comment by snohio** [comment]
If only we had our own website / subsite under orlandodevs.com 😛

**Comment by snohio** [comment]
Close here for now.
