### ISSUE TITLE
Organize "August DevOps Lean Beer" Event

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#3]
# Organize August DevOps Lean Beer Event

## User Story

As an organizer of Orlando DevOps Meetup, I would like to have organized, scheduled, and posted the Meetup Event on *August 17th at 7pm* in **Lake Nona**  so that we can start to move the monthly lean coffee / beer events around.

## Tasks

- [X] Find the Location [Boxi Park](https://www.google.com/maps/place/Boxi+Park+Lake+Nona/)
- [X] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [X] Promote on LinkedIn [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [X] Publish on ODevs Slack
- [x] Gather and Bring Materials
- [x] Create Slide Deck for ODevs Requirements
- [x] #10

## Extra Notes

> NOTE: This is the first time we are trying Boxi Park.

**Comment by mbuchoff** [comment]
https://www.meetup.com/orlando-devops/events/294924823/

**Comment by RecoveringChef** [comment]
after some scouting, will use Boxi Park. Double checked no live bands that night. There are covered areas in event of rain and several food choices (stalls).
Will see if I have permissions to add to meetup, and if not bug a Mike to add

**Comment by snohio** [comment]
I can add you as an Event Coordinator. I saw that it was posted. Thanks @mbuchoff (I am assuming.)

How is Boxi Park on non-music days?

Are there any other ToDo's for this (like gathering materials) or should we just close it?

**Comment by snohio** [comment]
Waiting on Paperwork from ODevs

**Comment by snohio** [comment]
We've review. 
Here are the [RESPONSES}(https://docs.google.com/forms/d/12bT79vtqNcULb6qoXPykesD6jmuFz5c3dv-rTYmBddo/edit#responses)
