### ISSUE TITLE
Create Q1-2024 Milestone

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#31]
# Create Q1-2024 Milestone (Milestone Maintenance)

## User Story

As a co-organizer of Orlando DevOps group, I would like to create a new Milestone to connect Issues with so that we have a good understanding of what we want to accomplish this quarter.

## Tasks

- [X] Create a new Q1 2024 Milestone (even though it is half over) DONE - [LINK](https://github.com/snohio/devopsorlando/milestone/3)
- [X] Move any open tasks from the old milestone to [Q1 24](https://github.com/snohio/devopsorlando/milestone/3)
- [X] Close [Q3-23](https://github.com/snohio/devopsorlando/milestone/2) and [Q4-24](https://github.com/snohio/devopsorlando/milestone/2)
- [x] Post Q4 Summary on LinkedIn and MeetUp

**Comment by snohio** [comment]
... I am waiting for a little gap. I might just skip it this quarter and post next quarter. We have a few things to post in the coming weeks.

**Comment by snohio** [comment]
Closing because it us quarter 2
