### ISSUE TITLE
February 13, 2024 - Lean DevOps at Ethos

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#32]
# Organize February 2024 DevOps Lean Beer Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on February 13th, 2024 at Ethos in Winter Park so that we can get our community together and learn about DevOps.

## Synapsis

What this month's meeting is about (or Lean Coffee)

## Tasks

- [x] Write up the Synapsis
- [X] Find the Location [Ethos Vegan Kitchen](https://www.google.com/maps/place/Ethos+Vegan+Kitchen/)
- [X] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/298413550/)
- [X] Have Brian post in [EventBrite](https://www.eventbrite.com/e/lean-green-devops-ethos-in-winter-park-tickets-801959812387)
- [x] Promote on LinkedIn [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296) @jehiers 
- [x] Publish on ODevs Slack [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE) @jehiers 
- [x] Gather and Bring Materials
- [x] Create Slide Deck for ODevs Requirements
- [x] Create Follow Up Survey [Here](https://forms.gle/GCtRp242YUZBjTiD6)

## Extra Notes

> NOTE:

**Comment by snohio** [comment]
Published the summary of the event and linked the slide deck over on [Slack](https://orlandodevs.slack.com/archives/C03DN28TXJ8). 
Great job team!
