### ISSUE TITLE
May 22nd, 2024 - Meetup Event - Terraform/Tofu Workshop

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#34]
# Organize Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *May 22nd, 2024* in **Credo (still need to confirm)** so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

Bring your laptops and be ready to go through some exercises together. We'll use OpenTofu to provision some resources onto a Cloud provider and upload simple web service onto it. My familiarity is .NET Core/Azure, but if anyone wants to go a different direction (ie NodeJS/AWS), we can also do that.

## Tasks

- [x] Write up the Synopsis
- [x] Confirm the location, [Slack request for Credo](https://orlandodevs.slack.com/archives/C06JYK7936H/p1713487037344059)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/299226778)
- [x] Have Mike Butler post in EventBrite - [posted](https://www.eventbrite.com/e/iac-deep-dive-workshop-deploying-your-infrastructure-as-code-with-tofu-tickets-905150558687)
- [x] Promote on LinkedIn - [posted](https://www.linkedin.com/feed/update/urn:li:activity:7197184307415707649?utm_source=share&utm_medium=member_desktop)
- [x] Publish on ODevs Slack [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE) - [posted](https://orlandodevs.slack.com/archives/C03E3J2BE/p1715942964116779)
- [x] Add a reminder to personal calendar to ping frequently (weekly) in the comments section
  - Encourage everyone to have done the following steps ahead of time:
    - Set up your private azure environment 
    - install azure cli
    - Confirm that `az account show` shows a valid Azure account
- [x] Gather and Bring Materials
- [ ] Create Slide Deck
  - Why do we need IaC? Give a detailed example of getting lost in the complexity without it.
  - Difference between IaC tools
    - Provisioning
      - Terraform/OpenTofu (functional)
      - Pulomi (imperative)
      - Cloudformations (functional)
      - VRO/VRA
    - Configuration Management
      - Ansible
      - Puppet
      - Chef
  - Resources
    - https://www.linode.com/docs/guides/terraform-vs-pulumi/
    - https://www.linode.com/docs/guides/introduction-to-infrastructure-as-code/
    - https://blog.xmi.fr/posts/terraform-vs-bicep/
- [ ] Create Follow Up Survey

## Extra Notes
- [x] Rebrand this.
  - From @snohio : 
  > Hey, the Feb 28th and May 22nd events can be a IaC Series. I'm going to dive more into the platform standards and configuring OS and Application standards. The Terraform event is more IaC from the provisioning side.
  > ...
  > We should really break it into a few. But we're already here..
  > 1) Building your image (with Packer or else)
  > 2) Deploying your Infrastructure with Code (Terraform)
  > 3) Updating and Enforcing your Policies (Chef Infra)
  > 4) Reporting and Validating your Configuration (Chef Inspec)
And how all of those incorporate security. It doesn't just live at the Edge, it is in every part of that.
- Common pattern: Infrastructure first, Terraform second.
  - Set up an ad-hoc scenario by hand with some complexity (so that the need for Terraform might be obvious), then show how to migrate
  - Consider Terify (`winget install aztfexport` or `brew install aztfexport`)
    - Takes a long time (TODO: time it)
    - Doesn't catch all resources (ie when I tested, it imported all keyvaults, but missed some, but not all secrets within them)
    - If you make the mistake of importing everything, you will have lots of garbage you have to mindfully remove a lot of the extras the come by default, ie security policies, hostnames, audits, etc) 
- Step 1: local state. Step 2: remote state
- Don't forget drift detection
- [Example project with tofu](https://github.com/mbuchoff/devops-vanilla-example/tree/main)

**Comment by snohio** [comment]
Updated the title and description to the new date of May 22nd. I updated the Meetup event to 6:30 rather than 7:00, primarily because you have this as a 3 hour event. People are going to want to leave by 9:30, I feel. Adjust if that is going to be too early to start presenting.

**Comment by snohio** [comment]
@mbuchoff - were you going to present? Is this the one that @mdaverde is going to present a general overview of Terraform / OpenTOFU? I would suggest to have at least a 30 minute presentation on what Terraform / OpenTOFU is.

**Comment by mbuchoff** [comment]
@snohio, for a presentation, I was thinking maybe a quick overview of the problem Tofu solves (ie paint a picture why use IAC at all) and a short demo of using it. If @mdaverde wants to present instead, I'm good with that.

Also, 6:30 sounds good to me instead of 7. I agree, 9:30 on a worknight will be late enough.

**Comment by mdaverde** [comment]
Not sure I agreed to this full talk but I am willing to help out

**Comment by mbuchoff** [comment]
@mdaverde, I don't think you did either, but wasn't sure if I missed (or misinterpreted) a conversation. Please don't feel like you have any commitments around this event.

**Comment by snohio** [comment]
Include in the presentation the difference between IaC being Terraform/OpenTofu, Cloudformations, VRO/VRA (THIS IS PROVISIONING) and IAC as Ansible, Puppet, Chef (THIS IS CONFIGURATION).

**Comment by mbuchoff** [comment]
@snohio, can you post [the Tofu event](https://www.meetup.com/orlando-devops/events/299226778) in EventBrite when you have a chance?

**Comment by mbuchoff** [comment]
@paulo-desouza, can you post [this](https://www.meetup.com/orlando-devops/events/299226778) in [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)?
