### ISSUE TITLE
February 28th, 2024 - Presentation at Credo Conduit

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#35]
# Organize February 28th, 2024 - IaC Deep Dive - Compliance and Platform Standards - Presentation at Credo Conduit

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on February, 28th 2024 at Credo Conduit so that we can deliver a great presentation to our community about Infrastructure as Code (from a platform standards perspective.)

## Synapsis

What is Infrastructure as Code? How can you configure your platform to standards and validate that they are compliant to your compute policies? In this Presentation, we are going to hear from an expert with over 8 years working with Chef Tools discussing how you can leverage Infrastucture and Compliance as Code approaches to better define and enforce platform standards.

## Tasks

- [x] Write up the Synapsis
- [x] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [x] Have Brian post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174) - [(done)](https://www.eventbrite.com/e/iac-deep-dive-compliance-and-platform-standards-tickets-843876817277)
- [x] Promote on LinkedIn [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [x] Publish on ODevs Slack [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [x] Order Food @mbuchoff - and let @snohio know if we need more money for this one.
  - [Slack conversation](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1708281134238729?thread_ts=1708280883.536769&cid=C06GBJJUQ6M)
  - Consider Lazy Moon
- [x] Gather and Bring Materials
- [x] Create Slide Deck for ODevs Requirements
- [x] Create Follow Up Survey

## Extra Notes

> NOTE: This is basically, my presentation of Chef in a very informal way. I am going to try to not deep-dive too much into the sales side of things and I will also talk about CINC which is the Community build of the Open Source code that creates the Chef binaries. Depending on interest, I might go into this a little too.  I'll have a better framework ready on February 27th and will post that in the comments. I **WILL** have some give-aways including some JBL Headphones,  a TILE or two and whatever else is left in my box..

**Comment by mbuchoff** [comment]
@mdaverde, circling the Slack conversation into here...

I have a 50% off Papa Johns card that doesn't have to be pizza. I can see on their website [bowls](https://www.papajohns.com/order/menu/Papa-bowls), [flatbread sandwiches](https://www.papajohns.com/order/menu/Papadias), [wings](https://www.papajohns.com/order/menu/Wings), and more. Given that we should expect 30ish people and we have a $50 budget from ODevs, we'll need to be a little stingy (or someone can lend me their credit card and the sky is the limit).

cc @snohio

**Comment by snohio** [comment]
I honestly think that after this weekend at code camp, we are going to have 45 -50. Maybe that's the optimist in me. I love the idea for BBQ. Let's do that.
Chef (me) is going to pay for it so < 300 I don't care. I'm also very serious about finding a mixologist for Mocktails.
Lets talk about it at OCC.

**Comment by mbuchoff** [comment]
> ... Chef (me) is going to pay for it ...

That opens up many doors, including 4-Rivers. I'll see you later today and we can talk about details.
