### ISSUE TITLE
March 23, 2024 - Hackathon

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#36]
# Organize Hackathon

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *March 24* in **Credo** so that we can do a project together.

## Synopsis

I'll bring breakfast from [Bagel King](https://www.bagelking.net/casselberry) (feel free to request bagels in the comments), but you are also welcome to bring your own food, whether from home or from an eDelivery service after you get here.

In the past few meetups, the idea of hackathons keep coming up. Let's try one out with Orlando DevOps. We tend to get a wide variety of people with unique skills, so this will be a good chance to leverage all of them.

We will hold the event in the Theater Room in the back of Credo.

This will be a small, manageable project that should take us 5 to 6 hours.
What will the project do? It's up to us. K8s, CI/CD, Monitoring, and ChatOps are just a few of the categories we can develop for.

It's safe to say we will have a shared GitHub repo but the rest remains open-ended. Generally, hackathons involve large crowds split into smaller groups. However, considering our typical turnout of 8-10 people, one big team will probably make more sense.

## Tasks

- [x] Write up the synapsis
- [x] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/298671294/)
- [x] Have Brian post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
  - [EventBrite link](https://www.eventbrite.com/e/devops-hackathon-feel-free-to-arrive-later-tickets-850314984007)
- [x] Promote on LinkedIn [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
  - [Corresponding post](https://www.linkedin.com/feed/update/urn:li:activity:7167592909368737792?utm_source=share&utm_medium=member_desktop)
- [x] Publish on ODevs Slack [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [x] Order Food
- [x] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes
- Idea: Some sort of automation to streamline the steps in [the event template](https://github.com/snohio/devopsorlando/blob/main/.github/ISSUE_TEMPLATE/meetup.md).

**Comment by snohio** [comment]
I have coffee with Brian Shacklett next Monday (the 26th) to talk about ODevs and general DevOps things. He has been working on the new site design and calendar visibility tool on the ODevs site. I've mentioned to him before that we could do a ODevs / ODO hackathon together to get the site updated and with the ability for anyone to publish and it would validate, ask for approval and publish with a Github Action. I'll let you know what comes of that.

**Comment by snohio** [comment]
Successful event. I'm not sure if we should gather feedback from this or not, but maybe?
