### ISSUE TITLE
April 24, 2024 - Skilling Up for your Next DevOps Job

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#37]
# Organize April 24th. Long Form Event - Skilling Up for your Next DevOps Job

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on April 24th, 2024 at **TBD** so that we can help folks skill up for their next DevOps Positions.

## Synopsis

Are you looking for work? About to complete your program or degree? Just tired of your current role? Join us at *Valencia College* on April 24th at 7:00 pm to hear from experts in the DevOps industry on what they look for in candidates when hiring and what you should do when looking for work.

Join us in this interview style presentation

## Tasks

- [X] Write up the synopsis
- [x] Line up speakers (Post who they are here)
- [x] Find the Location **NOTE THAT WE MAY WANT TO START THE EVENT AT 6:30 INSTEAD OF 7, SO CONSIDER THAT AS YOU'RE INVESTIGATING**
  - CREDO is a fallback while we investigate alternatives ([Slack request](https://orlandodevs.slack.com/archives/C06JYK7936H/p1712189989646269))
    - Valencia - Bharat
    - Rollins - Contact [Daniel Myers](mailto:dmyers@rollins.edu) - @mbuchoff - [email sent](https://mail.google.com/mail/u/0/?ik=2867433fe1&view=om&permmsgid=msg-a:r-8174967316127674389)
    - WP Library - $600 - @mbuchoff 
      - Remember to mention our 501c3 status
      - Jacob may be able to get TekSystems to sponsor ([Slack question](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1712440485973119), [Slack reply](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1712440583756569))
        - Should this be split into a separate issue?
    - Brewlando - @RecoveringChef 
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [x] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [x] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Order Food
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Presenters / Topics

- [x] What do you while you are looking for work. (@mdaverde / @snohio Podcast style interview?)
- [x] What Recruiters are looking for? [Tanner Roe](https://www.linkedin.com/in/tannermroe/) or [Michael Anderson](https://www.linkedin.com/in/michael-anderson-hays/)
- [x] Solution Providers (TekSystems? Protiviti? Accenture? Xebia!) [Esteban Garcia](https://www.linkedin.com/in/estebangarcia/)
- [x] Director / Manager Presentation - [Aaron Kraft](https://www.linkedin.com/in/aaron-kraft/) _OR_ IT Ditrector Adam Scheinberg from Massey.

**Comment by snohio** [comment]
Locations: 
- [ ] Valencia - Bharat
- [ ] Rollins
- [ ] WP Library - $600 - TekSystems Sponsor?? Jacob?
- [ ] Brewlando
- [ ] Conduit (Reserve as Backup)

**Comment by mbuchoff** [comment]
501c3 nonprofit

**Comment by mbuchoff** [comment]
@snohio, you mentioned a large room in the Winter Park Library to acomodate 50+ people. I don't see such a room on their [website](https://www.winterparklibrary.org/reserve-room). What am I missing?

**Comment by snohio** [comment]
https://www.winterparklibrary.org/rent-room
Edyth Bush Theater

**Comment by snohio** [comment]
I am doubting that they will make any cost reductions for non-profit organizations, but it is worth a try.

Here's where to contact:

Reservations may be made online or by contacting the Library at (407) 623-3300, ext. 5, or
emailing rooms@winterparklibrary.org. After a confirmed reservation, payment method must
be arranged/confirmed prior to event. Failure to pay by the deadline that is mutually agreed
upon and arranged by the Library and the renter will result in cancellation and the charge of
additional fees.

**Comment by mbuchoff** [comment]
Left a voicemail. We'll see.

**Comment by mbuchoff** [comment]
Just heard back. As suspected, they can only go down by 25% ($225/hour) and the rental would need to be finished by 8:30, however if we meet the following criteria, they would allow us to rent the room for free:
- 3 months out
- Allow the event to be public (which all of our events are)
- Fill out [this form](https://www.winterparklibrary.org/suggest-a-class) and get approved.

I've added this information to [devops-meetup-locations.md](https://github.com/snohio/devopsorlando/blob/main/devops-meetup-locations.md).

**Comment by snohio** [comment]
Quick update!
We have a good portion of this user story completed. I will handle the slide deck and survey. From a materials perspective, I'll bring my laptop. 

@mbuchoff - you have Pizza and such to arrange and can you verify that we will have **projector** and at least **two microphones** available (and 5 chairs for the roundtable at the end.) We do not really need a podium except to hold the laptop for the intro and exit slide deck.

We are at about 20 people right now, but I want to see us have at least 50 for this. I know it is a popular topic. If folks can market this, I'd appreciate it. The theater holds 350 or something crazy like that.

I am super excited about this one and I'm not even looking for a job!
