### ISSUE TITLE
Review Meetup Form to capture more information

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#38]
# Review Meetup Form to capture more information

## User Story

As a co-organizer of Orlando DevOps group, I would like to review requirements on the Meetup Form so that can gather more valuable data when folks register and attend our events and help prevent multiple sign ups and never shows, plus build our mailing list.

## Tasks

- [ ] Determine what we can add to Meetup Event Registrations
- [ ] Present to the Leadership team
- [ ] Add the requirements to the form (either permanent or each time. if Each Time, add that to the Meeting Issue Template)

**Comment by mdaverde** [comment]
![Screenshot 2024-04-09 at 11 55 35 AM](https://github.com/snohio/devopsorlando/assets/1067001/b60b80fd-5b3a-4236-a150-d172d4b29cb2)
