### ISSUE TITLE
May 8th, 2024 - Lean Beer 

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#40]
# Organize May 8th DevOps Lean Beer 

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Lean Beer on May 8th at Crooked Can so that we can enjoy the company.

## Synopsis

What this months meeting is about (or Lean Coffee)

## Tasks

- [x] Write up the synopsis
- [x] Find the Location
  - Event at [Axum Coffee](https://maps.app.goo.gl/D6vnyS1LG7hSmd4K6)
  - Eat at [The Whole Enchilada](https://maps.app.goo.gl/PfVTH95VtAqKT7vh9) afterward
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [x] Have @snohio post in EventBrite ([link](https://www.eventbrite.com/e/lean-coffee-devops-axum-in-winter-garden-tickets-893124588687?utm_source=eventbrite&utm_medium=email&utm_content=follow_notification&utm_campaign=following_published_event&utm_term=Lean+Coffee+DevOps+-+Axum+in+Winter+Garden&aff=ebemoffollowpublishemail&utm_experiment=follow_template.B))
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [x] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

**Comment by mbuchoff** [comment]
@RecoveringChef, just want to bump about Crooked Can. Do they have loud music on Wed nights?

**Comment by RecoveringChef** [comment]
Cool place. Plant St Market reminds me of Armature Works with different
food and drink options. But most were closed by 8:30 except the brewery and
a couple food stalls.

Live music and speakers all around most of the outside dining area, not
Boxi Park loud but still probably problematic.

Musician went off at 9:00 and house music came on but much lower volume.

Some tables down at the end by Brunos Oysters/ Barrel Room that seemed to
not have speakers.

We would need to get here early enough to drag a few tables together and
would be subject to weather.

Back up plan in case of weather is there is a Foxtail around the corner
with covered patio and indoor tables

**Comment by snohio** [comment]
I really want to attend this one, but I'm 50/50 going to San Francisco for the RSA Conference.

I added a link to Plant Street Market in the Description above. @mbuchoff - want to call them to see about reserving a private space? Not sure what they charge.

**Comment by mbuchoff** [comment]
@snohio, I left a message for Corporate events (someone took notes and will pass it on), but in the event that doesn't play out, let's come up with a Plan B and a cutoff time. I suggest [Starbucks on Lake Mary Blvd](https://maps.app.goo.gl/1z3CmoktKUD6tHgn8) and that we make a final decision one way or another by Friday.

**Comment by snohio** [comment]
Oh, I think if there are 10-12 you are probably fine just gathering there without any sort of reservations. I was more curious what they officially had and if they charged for it. If not, better to be official.

**Comment by mbuchoff** [comment]
What do you guys think about doing Lean Coffee at [Axum Coffee](https://maps.app.goo.gl/H2CubTa4dgpC9z7q9) from 7 to 9, then continuing across the street at [The Whole Enchilada](https://maps.app.goo.gl/1yC69hESM8WZKPcm9)?

**Comment by mbuchoff** [comment]
Adjusting the location todo item. For posterity, here was the old one:
> - [ ] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
>  - Consider Crooked Can in Winter Garden. @RecoveringChef will swing by on a Wednesday evening to see if there is loud music on a weeknight.
>  - [Crooked Can Market Street Info](https://crookedcan.com/plant-st-market/)
>  - Plan Your Corporate Event With Us!  [Call: (407) 456-7144](tel:+14074567144)

**Comment by mbuchoff** [comment]
@snohio, can you also crosspost [the upcoming Lean Coffee event](https://www.meetup.com/Orlando-DevOps/events/294924796) in EventBrite?
