### ISSUE TITLE
June 12th, 2024- Lean Bread

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#41]
# Organize June 12th, DevOps Lean Bread

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and post the Lean event on June 12th at **Panera, Oceola Parkway** so that we can have short form discussions and move the monthly lean coffee / beer events around.

## Synopsis

What this months meeting is about (or Lean Coffee)

## Tasks

- [ ] Write up the synopsis
- [ ] Location: Panera, Oceola Parkway (@RecoveringChef )
- [ ] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [ ] Have Brian post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
- [ ] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [ ] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Order Food
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
