### ISSUE TITLE
June 29th, 2024- Creating your first Open Source Contribution / Workshop

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#42]
# Organize MONTH DevOps Lean Beer (or) Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *DATE HERE* in **LOCATION HERE** so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

This event will be to help you find an open source project, fork, enhance and commit. 

## Tasks

- [ ] Write up the synopsis
- [ ] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [ ] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [ ] Have Brian post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
- [ ] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [ ] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Order Food
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
