### ISSUE TITLE
Reach out to other meetup groups for a joint event

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#44]
# Reach out to other meetup groups for a joint event

## User Story

As a co-organizer of Orlando DevOps group, I would like to organize a meetup event with other meetup groups so that we can attract new members and help our existing members become aware of new networking opportunities.

## Tasks

- [x] Confirm that the other organizers are alright with this
- [x] Create a list of groups we would like to reach out to
  - [Orlando Developers](https://www.meetup.com/orlandodevs/)
  - [Orlando AWS User Group](https://www.meetup.com/orlandoaws/)
  - [ONETUG - Orlando .NET User Group](https://www.meetup.com/onetug/)
  - [Google Developer Group Central Florida](https://www.meetup.com/gdg-central-florida/)
  - [Agile Orlando](https://www.meetup.com/agile-orlando/)
  - [WordPress Orlando](https://www.meetup.com/wordpress-orlando/)
  - [West Orlando WordPress Meetup](https://www.meetup.com/west-orlando-wordpress-meetup/)
  - [Project Codex](https://www.meetup.com/project-codex/)
- [ ] Create a template that includes suggested events (what), venues (where), and date/times (when).
  - Ideas for events
    - Presentation of what is DevOps
    - Presentation of what the other group does
    - Combined workshop, maybe involving CI/CDing or IACing onto the platform associated with the group (or JIRA tickets, in the case of Agile)
    - A social, plain and simple. Maybe two rounds of Lean Coffee, one associated with topics related to our group and one related to their's.
    > Hi, I'm from the [Orlando DevOps](https://www.meetup.com/Orlando-DevOps/) software engineering group. We're interested in putting on a joint event to let our members know about other groups, as well as letting their members know about ours. Is this something you'd be open to?
    > We're pretty open, but to get the ball rolling, here are some ideas:
    > - Presentation of what is DevOps
    > - Presentation of **INSERT OTHER GROUP HERE**.
    > - Combined workshop, maybe involving CI/CDing or IACing onto the platform associated with **OTHER GROUP (OR JIRA TICKETS, IN THE CASE OF AGILE)**.
    > - A social. For example often do Lean Coffee ([June 12](https://www.meetup.com/orlando-devops/events/301470062/), [May 8](https://www.meetup.com/orlando-devops/events/300676395/), [April 10](https://www.meetup.com/orlando-devops/events/299558046/)). We can mix topics relating to both our groups.
    > 
    > And here are some suggested dates:
    > 
    > - Wed, August 28
    > - Wed, Sept 11
    > - Sat, Sept 28
    > - Wed, Oct 9
    > - Wed, Oct 23
    > - Wed, Nov 13
    > 
    > We're not sticklers, so if you prefer some other idea/date/etc, feel free to suggest it. Thanks!
- [ ] Reach out to those groups
- [ ] Add calendar remembers to bump unanswered messages

**Comment by mbuchoff** [comment]
@snohio, @RecoveringChef, can you read over the template and the groups before I send anything out?
