### ISSUE TITLE
August 28, 2024 - BYOBugs

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#45]
# Organize July Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on August 28 so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

Many of the members of our group are working on their own personal project and have expressed interest in an event geared toward helping them solve some of the bugs they are coming across. This is especially relevant for the newer software engineers who are still learning how to troubleshoot.

## Tasks

- [ ] Write up the synopsis
    > Many of our members have their own personal projects (or contribute to open source) and get stuck trying to diagnose a bug. If this is you, or if you're someone who enjoys helping unblock others (or you want to come and observe the bugfixing process), we want you at our event.
    > 
    > Bring:
    > - Laptop
    > - If you are up against any bugs, be prepared to demonstrate those bugs
- [ ] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [ ] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/294924796)
- [ ] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
- [ ] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [ ] Confirm the location of the EventBrite event is correct.
- [ ] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [ ] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Order Food
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:

**Comment by mbuchoff** [comment]
Closing. Doing a [K8S event](https://github.com/snohio/devopsorlando/issues/49) instead.
