### ISSUE TITLE
July 24, 2024 - Show and Tell

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#46]
# Organize July DevOps Lean Beer (or) Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *July 24* in **Stardust**.

## Synopsis
> Working on an interesting project you'd like to share? Interested in learning about someone else's interesting project? Trying to solve xyz and want to talk about it with other software developers?
> 
> Internet is solid, parking is simple. Stardust Coffee serves food, so dinner is also an option.
> Food menu - https://stardustvideoandcoffee.wordpress.com/kitchen/our-menu/
> What this months meeting is about (or Lean Coffee)

## Tasks

- [x] Write up the synopsis
  - Based off our previous [Code and Coffee](https://www.meetup.com/Orlando-DevOps/events/293344314) event
  - Make the title _Show and Tell (aka Code and Coffee)_
- [x] Find the Location [Stardust](https://stardustvideoandcoffee.wordpress.com/)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/302102922) 
  - Sent an [email](https://mail.google.com/mail/u/0/#sent/DmwnWtDwjkLFbJvnMpjpGnQXWBFngqvNqDmkftpnbGNcsRqpBNkPmmhVgLVZNZzpRmbCjsScnPBv) to reserve some tables. I don't expect to hear back, but figured I'd at least give it a shot.
- [x] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174) - [Slack request](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1720918087500849)
- [ ] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [ ] Confirm the location of the EventBrite event is correct.
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296) - [post](https://www.linkedin.com/feed/update/urn:li:activity:7218054314223640576?utm_source=share&utm_medium=member_desktop)
- [x] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE) - [post](https://orlandodevs.slack.com/archives/C03DN28TXJ8/p1720918599034729)
- [x] Order Food (not necessary)
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
