### ISSUE TITLE
November 27, 2024- Golang Workshop

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#48]
# Organize November Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *DATE HERE* in **LOCATION HERE** so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

What this months meeting is about (or Lean Coffee)

## Tasks

- [ ] Write up the synopsis
- [ ] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/302103647)
- [ ] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
- [ ] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [ ] Confirm the location of the EventBrite event is correct.
- [ ] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [ ] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [ ] Order Food
- [ ] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
