### ISSUE TITLE
August 31, 2024 - Learn Kubernetes (K8S) together

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#49]
# Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *2024-08-31* in **Credo (or anywhere, really)**.

## Synopsis

There's been a lot of interest in doing a Kubernetes event. Although I don't have a strong enough background to put together a structured 101 workshop, hopefully between my surface level knowledge and everyone else's expertise, we can connect the pieces and gather steps for such a future event.

If you're new to Kubernetes, join us and we'll figure it out together. If you're more familiar with it, we could use your help!

## Tasks

- [x] Write up the synopsis
- [x] Find the Location [Venue request for Credo](https://orlandodevs.slack.com/archives/C06JYK7936H/p1723418118036319)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/302778333/?slug=orlando-devops&eventId=302778333)
- [x] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174) ([Slack message](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1723693217682709))
- [x] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [x] Confirm the location of the EventBrite event is correct.
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7097321959037751296)
- [x] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
- [x] Order Food - Order #2BF4438E, consisting of [The Bagel Tray](https://www.bagelking.net/catering#menu=catering-queens&item=the-bagel-tray&location=casselberry) from Bagel King. Pickup is 10am morning of.
- [x] Gather and Bring Materials
- [x] Create Slide Deck for ODevs Requirements
- [x] Create Follow Up Survey

## Extra Notes

> NOTE:
