### ISSUE TITLE
Research Github Org creation for Orlando DevOps

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#5]
# Orlando DevOps GitHub Repo

## User Story

As a co-organizer of Orlando DevOps group, I would like to research and possibly create a Github org specifically for the Orlando DevOps group so that we can keep all of the Hackathon, Orlando DevOps notes, Web content and anything else we do in a unified and transferable location.

## Tasks

- [x] Does Orlando Devs already have one that we should just get permissions to?
- [ ] Is there a cost associated with this if it is for a Non-profit organization?
- [ ] Do we need our non-profit information - if so this would be under ODevs and does that circle back to task number one.
- [ ] Create an Orlando DevOps Organization (if that is the decision) with @snohio @mbuchoff @RecoveringChef and @estebang

**Comment by mbuchoff** [comment]
This depends on whether we choose to join O'Devs. Should we make an item in this project for that conversation?

**Comment by mbuchoff** [comment]
@snohio, I sense there's not much enthusiasm around this task. Should we close it?

**Comment by snohio** [comment]
@mbuchoff - No. We'll either get access to the ODevs one or create one. We need a place to put this stuff besides my repo. We're kinda currently blocked on ODevs information. I also want to start some sort of basic website / whether that is full fledged site or just sitting behind github pages using 11ty (what ODevs uses) or Docusaurus or MKDocs. Something that is a central place for info.

**Comment by mdaverde** [comment]
Btw, GitHub provides free GitHub Team for organizations with 501(c)3 status

Also I wanted to add this link as a reference to a GitHub organization that already exists: https://github.com/OrlandoDevs

**Comment by mdaverde** [comment]
Here's the Eleventy site that is currently in use: https://github.com/jacquesfu/odevs-eleventy-starter 

Notably, not in the above org

**Comment by mbuchoff** [comment]
@mdaverde, links added to [odevs-resources.md](https://github.com/snohio/devopsorlando/blob/main/odevs-resources.md)

**Comment by mdaverde** [comment]
Also came across this subdomain: https://my.orlandodevs.com/  Not sure if its being used?

Another idea: we would ideally move this project into the OrlandoDevs GitHub org? Maybe something we can do at the Hackathon this weekend?

**Comment by snohio** [comment]
I am still trying to get access to the existing OrlandoDevs github org. There are currently 4 members of that org and none of them are still participating in Orlando Devs. Brian Shacklett is trying to get one of us added.

**Comment by snohio** [comment]
I have full access to the Orlando Devs github group. We can make a group decision on whether we want to migrate this repo to orlandodevs org.
