### ISSUE TITLE
Sept 11, 2024 - Lean Coffee

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#50]
# Organize Sept DevOps Lean Beer (or) Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *Sept 11* in **The Great Southern Box Food Company** so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

What this months meeting is about (or Lean Coffee)

## Tasks

- [x] Write up the synopsis
- [x] Find the [Location](https://maps.app.goo.gl/Q1yJpNv8roRXgFXt9)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/orlando-devops/events/303246073/?slug=orlando-devops&eventId=303246073)
- [x] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174)
  - [Slack message](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1725669015902589?thread_ts=1725412290.961869&cid=C06GBJJUQ6M)
- [ ] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [ ] Confirm the location of the EventBrite event is correct.
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7237981131189407744?utm_source=share&utm_medium=member_desktop)
- [x] Publish on ODevs Slack two weeks before the event [#Meetup](https://orlandodevs.slack.com/archives/C03E3J2BE)
  - [Published here](https://orlandodevs.slack.com/archives/C03DN28TXJ8/p1725669400640429)
- [x] Order Food
  - Not needed to order ahead
- [x] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
