### ISSUE TITLE
Nov 13, 2024 - Lean Beer

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#52]
# Organize Nov DevOps Lean Beer (or) Long Form Event

## User Story

As an organizer of the Orlando DevOps Community Group, I would like to have organized, scheduled, and posted the Meetup Event on *DATE HERE* in **LOCATION HERE** so that we can start to move the monthly lean coffee / beer events around.

## Synopsis

What this months meeting is about (or Lean Coffee)

## Tasks

- [x] Write up the synopsis
- [x] Find the Location ex. [Credo Conduit](https://www.google.com/maps/place/The+Conduit/)
- [x] Create the Event in Meetup. [Meetup Event Link](https://www.meetup.com/Orlando-DevOps/events/304138020)
- [x] Have @snohio post in [EventBrite](https://www.eventbrite.com/o/orlando-devs-15266001174) - [slack conversation](https://orlandodevs.slack.com/archives/C06GBJJUQ6M/p1729945800142549), [EventBrite link](https://www.eventbrite.com/e/lean-devops-beer-oviedo-brewing-company-tickets-1067608237979)
- [x] EventBrite is glitchy. Confirm the date/time on the new event is correct.
- [x] Confirm the location of the EventBrite event is correct.
- [x] Promote on LinkedIn two weeks before the event [Group Post](https://www.linkedin.com/feed/update/urn:li:activity:7257194374856413184?utm_source=share&utm_medium=member_desktop)
- [x] Publish on ODevs Slack two weeks before the event - [Slack post](https://orlandodevs.slack.com/archives/C03E3J2BE/p1730250261144129)
- [x] Order Food
- [x] Gather and Bring Materials
- [ ] Create Slide Deck for ODevs Requirements
- [ ] Create Follow Up Survey

## Extra Notes

> NOTE:
