### ISSUE TITLE
Create a Logo for Orlando DevOps

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#6]
# Create a Logo for Orlando DevOps

## User Story

As a co-organizer of Orlando DevOps group, I would like to have an Orlando DevOps logo so that can start creating content with it.

## Tasks

- [x] Find someone to take on the task
- [x] Create the Logo(s)
- [x] Get review from the O-DO group.
- [x] Approval from ODevs too while we are at it.
- [ ] Add files to GitHub repo ([link](https://github.com/snohio/devopsorlando/tree/main/logo))

## Extra Notes

See examples in the comments.

**Comment by mbuchoff** [comment]
- The idea of basing our logo on the O'Devs logo depend on whether we want to join O'Dev's (and vice versa). @snohio, can you add an issue on here for that conversation?

**Comment by snohio** [comment]
I'll ask Brian about the ODevs logo reuse on Friday. And yes, I'm not foreseeing any concerns with becoming an ODev Community Group. (That is what they are labelled.)

No, no objections to using DallE unless there would like license concerns or usage fees.

**Comment by snohio** [comment]
Orlando Devs Astronaut. Single color on transparent background:

https://orlandodevs.com/static/img/odev-logo-blue.png
https://orlandodevs.com/static/img/footer-odev.png

DevOpsDays Default Logo
https://d33wubrfki0l68.cloudfront.net/50d53b9c2614a631cc318dd92ed9d943d4b49977/e5ea9/img/event-logo-square.jpg

Something to between these two. The gears do not have to have any resemblance to the DoD one, only my suggestion is to fill the helmet with gears instead of >_  . (With approval)

**Comment by mbuchoff** [comment]
Filling in the helmet with gears for our logo sounds good to me.

**Comment by snohio** [comment]
@mbuchoff - I found some high quality logos on the [orlando-devs repo](https://github.com/OrlandoDevs/orlando-developers/tree/master/assets) for the old old website. We got clearance from @remotesynth to go ahead, so lets see if we can get this done soon.
There are even .ai and .eps - Adobe Illustrator files there too.

![blank odevs](https://github.com/OrlandoDevs/orlando-developers/blob/master/assets/orlandoDevs-logo-KO-08.png)

**Comment by mbuchoff** [comment]
Very cool! I'll get started on it over the next few days.

**Comment by mbuchoff** [comment]
@snohio, to get started, I'm using a free 7-day trial. The month-to-month price isn't too much ($30), so I can resubscribe as needed, but if you know of an account I can use instead, that'd be even better.

**Comment by snohio** [comment]
Check with @RecoveringChef on his idea for the logo.

**Comment by mbuchoff** [comment]
Will do. FWIW, I already messed around with it a little. Here's what I have so far in case we want to go this direction. Among other things, I need to crop the left side out.
![orlando devops](https://github.com/snohio/devopsorlando/assets/13501758/57d40d6b-fc4d-4d3c-90e7-8427e4f6bc85)

**Comment by snohio** [comment]
Dan's idea is to make the Devops Infinity loop out of roller coaster track. Inside the left circle is the ODevs helmet untouched and the right side is full of gears.

**Comment by snohio** [comment]
![image](https://github.com/snohio/devopsorlando/assets/24615387/d0148041-6d2f-4f0b-9833-d401fa0065dc)
![image](https://github.com/snohio/devopsorlando/assets/24615387/903f8d11-4b2c-4318-96ae-d639c29202a0)

**Comment by RecoveringChef** [comment]
paid for a fivver guy that did the tampa devs logo and sent over the request with samples and idea. should get drafts in 24-48 hours

**Comment by snohio** [comment]
Hey, I know that some of these are not that much but keep this in mind as you draw out of pocket. Part of the reason to be under ODevs is that 401c3 thing. The money we spend should be tax deductible at the end of the year. So once our papers are signed, we can use that.

**Comment by snohio** [comment]
## Previews

![Preview-01](https://github.com/snohio/devopsorlando/assets/24615387/e8411c04-45f5-445e-af29-d6ee9624ac56)
![Preview-02](https://github.com/snohio/devopsorlando/assets/24615387/a5d07465-2f2d-4cbb-abe5-2a4c3c0dc7be)

## These are Transparent PNGs, hence not seeing the background.

- [ ] ![Orlando DevOps-03](https://github.com/snohio/devopsorlando/assets/24615387/e76bd3c9-6f5b-4e48-a28c-2813509fa160)
- [ ] ![Orlando DevOps-04](https://github.com/snohio/devopsorlando/assets/24615387/25f383ff-f98b-4f83-b19c-9d28419f0873)
- [ ] ![Orlando DevOps-05](https://github.com/snohio/devopsorlando/assets/24615387/20a1435f-b0a5-43f3-aeb4-7baa7c204ec1)
- [ ] ![Orlando DevOps-06](https://github.com/snohio/devopsorlando/assets/24615387/616da325-510b-4ad8-91d6-f0cb38436736)

## These are the JPGS that match

- [ ] ![Orlando DevOps-03](https://github.com/snohio/devopsorlando/assets/24615387/f1b79dc7-c808-4828-98c0-625a31322921)
- [ ] ![Orlando DevOps-04](https://github.com/snohio/devopsorlando/assets/24615387/031ae47b-2816-46ca-9f92-176ada61878c)
- [ ] ![Orlando DevOps-05](https://github.com/snohio/devopsorlando/assets/24615387/5156c7a8-5599-4de3-b4c5-0a447f37f00a)
- [ ] ![Orlando DevOps-06](https://github.com/snohio/devopsorlando/assets/24615387/c31d8897-600a-4d4d-bb3c-107ce071ecf5)

> Check the boxes that we thing we should use / focus on. Leave comments about design here as well in comments.

**Comment by RecoveringChef** [comment]
we get 3 revisions to the designs. I have requested the first revision with the things Mike B ((@snohio )that's not confusing) and I discussed.

**Comment by mbuchoff** [comment]
To add to the confusion, both Mikes are "Mike B"

**Comment by snohio** [comment]
So, it's `snohio` because back at the beginning of this century, I picked up snowboarding in Ohio. We didn't have much, but it was still fun. I started a community (go figure) of Ohio Snowboarders to meet up with and created a website and had a forum and updated snow reports. We called it Snohio for the Snowboard Network of Ohio. I still own snohio.com and snohio@gmail.com.

Here was the logo..
![image](https://github.com/snohio/devopsorlando/assets/24615387/5e7dc4bd-f76e-4f93-b1cb-64208aac9acc)
and
![image](https://github.com/snohio/devopsorlando/assets/24615387/85b10fe3-996d-47eb-b4de-9ce57d0d3497)

**Comment by snohio** [comment]
## Previews

![Preview2-01](https://github.com/snohio/devopsorlando/assets/24615387/61fd357f-8e31-4d6f-b0b8-8daf61cd0b82)
![Preview2-02](https://github.com/snohio/devopsorlando/assets/24615387/47de32f3-ca01-4282-90c9-d79ecf55b75b)

## Transparencies

![Orlando DevOps2-03](https://github.com/snohio/devopsorlando/assets/24615387/19b217ce-3b69-4a7c-92c5-ae597f48a653)
![Orlando DevOps2-04](https://github.com/snohio/devopsorlando/assets/24615387/986054b6-8b8a-40e0-99a9-2967a73e6752)
![Orlando DevOps2-05](https://github.com/snohio/devopsorlando/assets/24615387/3c759eee-6990-4229-b461-0e9d14ab9522)
![Orlando DevOps2-06](https://github.com/snohio/devopsorlando/assets/24615387/5157154f-0420-4ec8-a24c-a991537a032b)

## JPG

![Orlando DevOps2-03](https://github.com/snohio/devopsorlando/assets/24615387/64dfd35b-536d-4736-9e79-d99599601198)
![Orlando DevOps2-04](https://github.com/snohio/devopsorlando/assets/24615387/7220adcf-ab75-48c7-a525-4d8c6b855bcc)
![Orlando DevOps2-05](https://github.com/snohio/devopsorlando/assets/24615387/67623adb-d72b-4f86-997c-de70a1762318)
![Orlando DevOps2-06](https://github.com/snohio/devopsorlando/assets/24615387/d26d8fef-bfa5-4e3d-b4cb-0903cbc3ad8d)

**Comment by snohio** [comment]
I think these are good. I do think we should throw them by the ODevs folks just to be sure. @remotesynth what do you think?

**Comment by snohio** [comment]
I created an image for the stickers that is a bit more aligned. I say we go with this Orlando DevOps2 set. We can make small tweaks from there and hey, it's just a logo for a Community Group. We can change it up whenever we want.. It currently has all of the elements, and I do like it.

@RecoveringChef - if they can update 03 image in the zip pack to be the inverse of 5, that would be great. I think it is correct in the .eps file. 

When that is done and in our Drive and maybe also in this repo, let's close this issue. Amazing work on this all around!

**Comment by snohio** [comment]
Everything is approved. We are good other than getting that 03 image updated in the pack.

**Comment by RecoveringChef** [comment]
I have the hi res files from the designer

**Comment by mbuchoff** [comment]
@RecoveringChef, where can I get the high-res files? Do you think it'd be a good idea to reorder more sample stickers based on them? I had previously ordered them based on one of the other attached images in this page?

**Comment by snohio** [comment]
The one we sent, I modified to keep the sizes the same. It should be high enough quality for the stickers unless you think that the pixels could be tighter.

**Comment by mbuchoff** [comment]
Can we close this?

@RecoveringChef, don't forget to log what you spent [here](https://github.com/snohio/devopsorlando/edit/main/expenses.md).

**Comment by snohio** [comment]
@RecoveringChef Did we ever get the file .ps (.eps) and .jpg/.png with the corrected wordless white background image fixed? Everything I have has the backwards coaster.

**Comment by snohio** [comment]
Uploaded to /docs. @snohio will move it later.
