### ISSUE TITLE
Officially Join Orlando Devs as a "Community"

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#7]
# Officially Join Orlando Devs as a "Community"

## User Story

As a co-organizer of Orlando DevOps group, I would like to officially join Orlando Devs (ODevs) as a Community Group [About Them](https://orlandodevs.com/about/) so that we can leverage their 501(c)(3) non-profit status for events and coverage, resources such as Credo Conduit and Slack, and access to more folks that might be interested in the Security and Ops side of the industry.

## Tasks

- [X] Internally discuss pros and cons to become a Community Group of O-Devs
- [X] Make a decision to become a Community Group of O-Devs

If that is YES:

- [X] Set up a meeting with O-Devs president, Brian Rinaldi (August 11th at Noon)
- [x] Complete any paperwork or else needful for officially becoming a Community group
- [x] Add a member of our Orlando DevOps to their Orlando Devs Board of Advisors (@snohio)
- [x] Let people know on Slack that we have joined and provide more information
- [x] We should also publish on our socials.

## Extra Notes

> NOTE: There probably are a lot of questions or just follow up actions to take place as a result of this US. Let us try to track those as best as we can here.

**Comment by snohio** [comment]
Everything went well at the lunch meeting. There were discussions about non-profit and such that Brian took back to the executive board. Agreed to all but will need deeper discussions if we get to the DevOpsDays reality.

Brian was going to check today (Monday 8/14) to see what needed to be done to make it official. We'll want to get this done by Thursday for the Lean Coffee at Boxi.

**Comment by snohio** [comment]
## UPDATE 09/06/23

* The Google Form was completed by at least two of us. I did suggest to Lauren a few changes I'd make to the form. Hopefully she was not put off. 😛 
* There was an ask to add Lauren, Jacques and Brian as Co-organizers or maybe just Schedulers to our Meetup site. I'm probably fine with that, but will meet to discuss. I'm not sure Lauren was quite aware of how much we have our shit together. And much like the last comment, I hope she isn't put off by that.
* I'd still like to be on the Board of Advisors, I will ask that on Friday. Personally I think everyone who brings in a Community Group should have a member on the Board of Advisors and also be asked to participate in 'x' number of ODevs activities.
* Once that is all done, we can unblock and promote and move this to DONE!

**Comment by mbuchoff** [comment]
Is this issue still blocked?

**Comment by snohio** [comment]
@mbuchoff we need to get #4 posted in Meetup and Lauren will get it posted elsewhere and then @remotesynth will announce the joining on their Slack channel.

**Comment by RecoveringChef** [comment]
Can this be moved to done. I thought we were fully official now?

**Comment by snohio** [comment]
- [ ] Let people know on Slack that we have joined and provide more information
- [ ] We should also publish on our socials.

When those two things get done. Lauren said Brian would say something when we post our next meetup. So let's let Brian know he can do that then on our LinkedIn Group make the announcement, then we are done.
