### ISSUE TITLE
Learn about ODevs resources

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#8]
# Learn about ODevs resources

## User Story

As a co-organizer of Orlando DevOps community group, I would like to discover and learn about the things in the tasks from Orlando Devs so that we can leverage the tools and resources that can be shared as opposed to creating our own so that we can same time and/or money.

## Tasks

- [x] [O'Devs GitHub repo](https://github.com/OrlandoDevs/orlando-developers)
- [x] Is there a SurveyMonkey Account for Orlando Devs
- [x] Can we utilize the Astronaut logo and replace the >_ with gears? [DoD Logo Guide](https://devopsdays.org/organizing#designing-a-local-event-devopsdays-logo)
- [x] [Slides](https://drive.google.com/drive/folders/1sgSKhyotxzvBFIRLIEIqS57i3u9sneZT?usp=sharing)
- [x] Is there a Constant Contact or other Email tracking tool?
- [ ] Results of [speaker forms](https://docs.google.com/forms/d/e/1FAIpQLSezKdJzaTbio7kEoA141YWNyVpViMsiM4ekRI9BH3jl0kJe3Q/viewform)?
- [ ] What Socials does Orlando Devs use? (We want to create our own but we should be members of each other)
- [x] Is there a Orlando Devs Community Group meeting - annual or whatnot?
- [x] Patreon - send all folks to one? Create our own? 
- [x] Eventbrite to have "pay" registration / tickets. This WILL be required if we get to DevOpsDays level or even like 50+ person registrations. This helps with tracking too.
- [ ] Google Workspace for Non-Profit ?
- [x] Common Room? (10k / yr)
- [x] Meetup API OAuth
- [x] Add all this information to [odevs-resources.md](https://github.com/snohio/devopsorlando/blob/main/odevs-resources.md)

## Extra Notes

> NOTE: Ask these questions at meeting #7

**Comment by snohio** [comment]
No SurveyMonkey but they use Google Docs

**Comment by mbuchoff** [comment]
[Meetup Forms folder](https://drive.google.com/drive/folders/1Ac4UdxOGa-2KoqHzKm9EsLO3_SsbP8WV)
- [ODevs Speaker Form](https://docs.google.com/forms/d/1svC9OsugW96qzjNaRsHplWYcGCmMm5HSNoc8Ymxj22U/edit) - About the speaker, not about the speech
- [Meetup Review](https://docs.google.com/forms/d/10oc6gtSLSweyXsQ9weGdPkDTcz3RzuhibKF7gVNmN3A/edit) - Very general "did you like it and why"-ish sort of questions
- [Join ODevs Slack](https://docs.google.com/forms/d/1sEs1Vo57XaaLcO7_jPluQZHB77J8XGi9VEvHG-ETI48/edit)
- [ODevs Volunteer Form](https://docs.google.com/forms/d/1bKW8L_Sw8k8n8vLBJG_Y6-VtDkDp-wDXdr2ywh8LE9k/edit)
