### ISSUE TITLE
🛑 Create Social Media Groups / Accounts for Orlando DevOps

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#9]
# Create Social Media Groups / Accounts for Orlando DevOps

## User Story

As a co-organizer of Orlando DevOps group, I would like to create social groups / accounts so that can better spread the word about our events outside of just Meetup notifications and keep people informed on what we are up to

## Tasks

- [ ] Based on results from a survey, figure out the best socials to participate in
- [ ] Create Social Groups or Accounts where appropriate (Use chart below)
- [x] Look at [Common Room](https://www.commonroom.io/) as a tool to help manage and measure socials
- [ ] Send notifications to all constituents to connect and join!

| Social Network | Group / Acct Name | Link Directly To | Created | Shared | Connected to CR |
|-|-|-|-|-|-|
| LinkedIn | Orlando DevOps Community Group | https://www.linkedin.com/groups/12876376/ | Yes | No | Cost Associated |
|Example | Orlando DevOps | https://linqapp/orlando_devops|No|No|No|
|Email List (possibly MailChimp) based on [survey results](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit?usp=drive_web) | Orlando DevOps | TBD | No | No | TBD

## Extra Notes

> NOTE: We will need to coordinate and time the release of these IMO. I don't want to just jump right away here, but we need to start thinking about it.  Also, we should check if there are already existing ones and try to capture that info.

**Comment by snohio** [comment]
# Common Room Information

## Overview

I checked out [CommonRoom](https://commonroom.io/) a bit. It is kind of cool in that it lets you collect information from all the things talked about in Slack and Twitter, Github, Discorse, Discord, Stack Overflow, and create integrations with Zapier which I haven't played with. If we wanted to get information back from Meetup, LinkedIn and some other of the premium sites, or create more than a couple of reports or workflows, it'll cost us... A lot... We do get 50% off the price, but that takes us to 10k. [Here is the pricing](https://www.commonroom.io/pricing/)

The sales guys I talked to was very helpful and he suggested that the free service would probably do most of what we wanted. With some work, we might even be able to use Zapier to gather addition info. 

## Take Away

Anyway, the bit take away you get from the tool is data on where you are being talked about. Think of it as impressions. While this is incredibly useful - especially to understand if there is enough interest in doing a conference and if we do, how much people are talking about it.

Is it worth 10k? Probably not. Unless all of O Devs would be interested in it, which again, is only worth it if you have time to analyze the data. 😸

**Comment by snohio** [comment]
🛑 - Currently blocked awaiting some Survey Results so that we know where to target. I don't really want to manage a X account unless people actually still use it (for instance.)

**Comment by snohio** [comment]
We are intersted in maybe doing X and/or FB / Insta. Look for a Social Media manager (a Zoomer)

**Comment by snohio** [comment]
Assigned to @jehiers . Work with @snohio about thoughts. Let's find a time to connect.

**Comment by snohio** [comment]
@jehiers - let's setup a quick call the week of 2/12 to discuss further
